# Generated by Django 2.1.7 on 2019-05-28 13:12

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_issue'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='description',
            field=models.CharField(default='description is not defined.', max_length=800),
        ),
        migrations.AddField(
            model_name='issue',
            name='objective',
            field=models.CharField(default='Objective is not defined.', max_length=400),
        ),
        migrations.AddField(
            model_name='issue',
            name='priority',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='issue',
            name='submitted_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 28, 13, 12, 12, 901424, tzinfo=utc), verbose_name='date submitted'),
        ),
    ]
