# Generated by Django 2.1.7 on 2019-05-28 13:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20190528_2212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='submitted_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date submitted'),
        ),
    ]
