# Generated by Django 2.1.7 on 2019-05-29 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_auto_20190529_2044'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='review',
            field=models.CharField(choices=[('Draft', 'Draft'), ('Ready to review', 'Ready to review'), ('Approved', 'Approved')], default='Draft', max_length=15),
        ),
    ]
