# Generated by Django 2.1.7 on 2019-05-29 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_issue_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='status',
            field=models.CharField(choices=[('Open', 'Open'), ('Progress', 'In Progress'), ('Done', 'Done')], default='Open', max_length=8),
        ),
    ]
