# Generated by Django 2.1.7 on 2019-05-29 12:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_auto_20190529_2109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='submitted_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='submitted date'),
        ),
    ]
